"""student educations.

Revision ID: 0acc7b6e123e
Revises: e1d0ce077cb4
Create Date: 2022-01-08 10:36:54.061782

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0acc7b6e123e"
down_revision = "e1d0ce077cb4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "educations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("institution_name", sa.String(), nullable=False),
        sa.Column("studies_programme", sa.String(), nullable=False),
        sa.Column("starting_date", sa.Date(), nullable=False),
        sa.Column("ending_date", sa.Date(), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_educations_id"), "educations", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_educations_id"), table_name="educations")
    op.drop_table("educations")
    # ### end Alembic commands ###
