"""student profile.

Revision ID: 7ad5213cc3c6
Revises: 7c8f7ddee2d6
Create Date: 2022-01-08 12:17:03.661063

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7ad5213cc3c6"
down_revision = "7c8f7ddee2d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("birthdate", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_students_id"), "students", ["id"], unique=True)
    op.create_table(
        "educations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("institution_name", sa.String(), nullable=False),
        sa.Column("studies_programme", sa.String(), nullable=False),
        sa.Column("starting_date", sa.Date(), nullable=False),
        sa.Column("ending_date", sa.Date(), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_educations_id"), "educations", ["id"], unique=False)
    op.create_table(
        "volunteerings",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.String(), nullable=False),
        sa.Column("starting_date", sa.Date(), nullable=False),
        sa.Column("ending_date", sa.Date(), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_volunteerings_id"), "volunteerings", ["id"], unique=False)
    op.drop_column("users", "user_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("user_type", sa.VARCHAR(length=7), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_volunteerings_id"), table_name="volunteerings")
    op.drop_table("volunteerings")
    op.drop_index(op.f("ix_educations_id"), table_name="educations")
    op.drop_table("educations")
    op.drop_index(op.f("ix_students_id"), table_name="students")
    op.drop_table("students")
    # ### end Alembic commands ###
