"""company domain; internship deadline and period.

Revision ID: a928b948fd07
Revises: b9374e7a1d0e
Create Date: 2022-01-09 17:28:25.009340

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a928b948fd07"
down_revision = "b9374e7a1d0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # https://medium.com/the-andela-way/alembic-how-to-add-a-non-nullable-field-to-a-populated-table-998554003134
    op.add_column("companies", sa.Column("domain", sa.String(), nullable=True))
    op.execute("UPDATE companies SET domain = ''")
    op.alter_column("companies", "domain", nullable=False)

    op.add_column("internships", sa.Column("deadline", sa.Date(), nullable=True))
    op.add_column("internships", sa.Column("starting_date", sa.Date(), nullable=True))
    op.add_column("internships", sa.Column("ending_date", sa.Date(), nullable=True))

    op.execute(
        "UPDATE internships SET deadline = CURRENT_DATE + INTERVAL '30 DAY', starting_date = CURRENT_DATE, ending_date = CURRENT_DATE + INTERVAL '30 day'"
    )
    op.alter_column("internships", "deadline", nullable=False)
    op.alter_column("internships", "starting_date", nullable=False)
    op.alter_column("internships", "ending_date", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("internships", "ending_date")
    op.drop_column("internships", "starting_date")
    op.drop_column("internships", "deadline")
    op.drop_column("companies", "domain")
    # ### end Alembic commands ###
