"""fix birthdate type.

Revision ID: b5553c92f47c
Revises: dba7647b3b9b
Create Date: 2022-01-08 12:07:28.877790

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b5553c92f47c"
down_revision = "dba7647b3b9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students",
        "birthdate",
        existing_type=sa.VARCHAR(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students",
        "birthdate",
        existing_type=sa.Date(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
