"""student volunteering.

Revision ID: dba7647b3b9b
Revises: 0acc7b6e123e
Create Date: 2022-01-08 10:50:46.954953

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "dba7647b3b9b"
down_revision = "0acc7b6e123e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volunteerings",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.String(), nullable=False),
        sa.Column("starting_date", sa.Date(), nullable=False),
        sa.Column("ending_date", sa.Date(), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_volunteerings_id"), "volunteerings", ["id"], unique=False)
    op.add_column("students", sa.Column("first_name", sa.String(), nullable=False))
    op.add_column("students", sa.Column("last_name", sa.String(), nullable=False))
    op.add_column("students", sa.Column("birthdate", sa.Date(), nullable=False))
    op.add_column("students", sa.Column("description", sa.String(), nullable=False))
    op.add_column("students", sa.Column("phone", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "phone")
    op.drop_column("students", "description")
    op.drop_column("students", "birthdate")
    op.drop_column("students", "last_name")
    op.drop_column("students", "first_name")
    op.drop_index(op.f("ix_volunteerings_id"), table_name="volunteerings")
    op.drop_table("volunteerings")
    # ### end Alembic commands ###
