"""student profile.

Revision ID: e1d0ce077cb4
Revises: 7c8f7ddee2d6
Create Date: 2022-01-07 16:51:26.092314

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e1d0ce077cb4"
down_revision = "7c8f7ddee2d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_students_id"), "students", ["id"], unique=True)
    op.drop_column("users", "user_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("user_type", sa.VARCHAR(length=7), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_students_id"), table_name="students")
    op.drop_table("students")
    # ### end Alembic commands ###
