name: Pull Request

# Events that trigger a workflow:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    branches:
      - master
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      # - name: Load cache (if exists)
      #   uses: actions/cache@v2.1.3
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip
      #     restore-keys: ${{ runner.os }}-pip
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-root -vvv
      - name: Run checkers
        run: |
          set -e
          poetry shell
          isort --check-only .
          pydocstyle .
          black --check .
          pylint backend
